project:
  type: website
  output-dir: docs

website:
  title: "Jeramia Valentine's Git-Hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - favorites.qmd
      - hobbies.qmd

format:
  html:
    theme: vapor
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "white"
    linkcolor: "white"
    monofont: courier new
#    backgroundcolor:
    css: styles.css
    toc: true



