project:
  type: website
  output-dir: docs

website:
  title: "Jeramia Valentine's Git-Hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - favorites.qmd

format:
  html:
    theme: quartz
    mainfont: arial
    fontsize: 1rem
    fontcolor: "black"
    linkcolor: "blue"
    monofont: courier new
#    backgroundcolor:
    css: styles.css
    toc: true



